using System.Collections.Generic;
using System.IO;
using System.Text;
using Heddle.Precompiled;
using Heddle.Precompiled.CompiledForm;

namespace Heddle.Tool.Compile
{
    /// <summary>Prints the generated source: the assembly marker naming the artifact class, the
    /// artifact class opening the embedded resource and carrying the generated site table, one
    /// typed static method per member accessor, native expression and embedded C# site, and one
    /// typed wrapper class per template with the three <c>Generate</c> overloads. Each wrapper
    /// binds once, on first call, through the typed entry point and forwards to the bound
    /// template; nothing is cached on failure, so a later call after the host fixes configuration
    /// binds. A site the printer declined has no method: the loader rebuilds it from data.</summary>
    internal static class SourceEmitter
    {
        internal static void Write(string sourceOut, string generatedNamespace,
            IReadOnlyList<EmittedTemplate> templates, string engineVersion, string artifactDigest)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated>Printed by heddle compile; do not edit.</auto-generated>\n");
            sb.Append("#pragma warning disable\n");
            sb.Append("using System;\n");
            sb.Append("using System.IO;\n");
            sb.Append("using Heddle.Precompiled;\n");
            AppendCSharpUsings(sb, templates);
            sb.Append('\n');
            sb.Append("[assembly: HeddleCompiledTemplates(typeof(")
                .Append(generatedNamespace).Append(".HeddleArtifact), ")
                .Append(PrecompiledSchema.CompiledFormSchemaVersion).Append(", \"")
                .Append(engineVersion).Append("\")]\n");
            sb.Append('\n');
            sb.Append("namespace ").Append(generatedNamespace).Append("\n{\n");
            sb.Append("    internal sealed class HeddleArtifact : IHeddleCompiledArtifact, IPrecompiledSiteTable\n");
            sb.Append("    {\n");
            sb.Append("        public Stream OpenArtifact()\n");
            sb.Append("        {\n");
            sb.Append("            var stream = typeof(HeddleArtifact).Assembly\n");
            sb.Append("                .GetManifestResourceStream(\"Heddle.CompiledForm\");\n");
            sb.Append("            if (stream == null)\n");
            sb.Append("                throw new InvalidOperationException(\"Embedded resource \" +\n");
            sb.Append("                    \"'Heddle.CompiledForm' is missing from '\" +\n");
            sb.Append("                    typeof(HeddleArtifact).Assembly.FullName + \"'.\");\n");
            sb.Append("            return stream;\n");
            sb.Append("        }\n");
            sb.Append('\n');
            sb.Append("        public string ArtifactDigest => \"").Append(artifactDigest ?? string.Empty).Append("\";\n");
            AppendSiteFields(sb, templates);
            sb.Append('\n');
            sb.Append("        public bool TryGetSite(string templateContentHash, int templateIndex, int siteOrdinal, out Delegate site)\n");
            sb.Append("        {\n");
            sb.Append("            site = null;\n");
            foreach (var template in templates)
                Sites.SitePrinter.AppendTable(sb, template.ContentHash, template.TemplateIndex, template.Sites);
            sb.Append("            return false;\n");
            sb.Append("        }\n");
            AppendSiteMethods(sb, templates);
            sb.Append("    }\n");
            foreach (var template in templates)
            {
                if (!template.EmitWrapper)
                    continue;
                sb.Append('\n');
                sb.Append("    public static class ").Append(template.Sanitized).Append('\n');
                sb.Append("    {\n");
                sb.Append("        private static HeddleTemplate _bound;\n");
                sb.Append("        private static readonly object _bindLock = new object();\n");
                sb.Append('\n');
                sb.Append("        private static HeddleTemplate Bound()\n");
                sb.Append("        {\n");
                sb.Append("            var bound = _bound;\n");
                sb.Append("            if (bound == null)\n");
                sb.Append("                lock (_bindLock)\n");
                sb.Append("                {\n");
                sb.Append("                    bound = _bound;\n");
                sb.Append("                    if (bound == null)\n");
                sb.Append("                    {\n");
                sb.Append("                        bound = PrecompiledTemplates.BindTyped(\n");
                sb.Append("                            typeof(HeddleArtifact).Assembly,\n");
                sb.Append("                            \"").Append(Escape(template.Key)).Append("\",\n");
                sb.Append("                            typeof(").Append(template.ModelTypeName).Append("));\n");
                sb.Append("                        _bound = bound;\n");
                sb.Append("                    }\n");
                sb.Append("                }\n");
                sb.Append("            return bound;\n");
                sb.Append("        }\n");
                sb.Append('\n');
                sb.Append("        public static string Generate(").Append(template.ModelTypeName)
                    .Append(" model, object chained = null, object callerData = null)\n");
                sb.Append("        {\n");
                sb.Append("            return Bound().Generate(model, chained, callerData);\n");
                sb.Append("        }\n");
                sb.Append('\n');
                sb.Append("        public static void Generate(").Append(template.ModelTypeName)
                    .Append(" model, TextWriter writer, object chained = null, object callerData = null)\n");
                sb.Append("        {\n");
                sb.Append("            Bound().Generate(model, writer, chained, callerData);\n");
                sb.Append("        }\n");
                sb.Append('\n');
                sb.Append("        public static void Generate(").Append(template.ModelTypeName)
                    .Append(" model, System.Buffers.IBufferWriter<byte> writer, ")
                    .Append("object chained = null, object callerData = null)\n");
                sb.Append("        {\n");
                sb.Append("            Bound().Generate(model, writer, chained, callerData);\n");
                sb.Append("        }\n");
                sb.Append("    }\n");
            }

            sb.Append("}\n");
            AppendCSharpClasses(sb, templates);
            string directory = Path.GetDirectoryName(sourceOut);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);
            File.WriteAllText(sourceOut, sb.ToString(), new UTF8Encoding(false));
        }

        private static void AppendCSharpUsings(StringBuilder sb, IReadOnlyList<EmittedTemplate> templates)
        {
            var seen = new HashSet<string>(System.StringComparer.Ordinal);
            foreach (var template in templates)
            {
                if (template.CSharpUsings == null)
                    continue;
                foreach (var ns in template.CSharpUsings)
                {
                    if (string.IsNullOrWhiteSpace(ns) || !seen.Add(ns))
                        continue;
                    sb.Append("using ").Append(ns).Append(";\n");
                }
            }
        }

        /// <summary>One static delegate field per printed site: creation happens once per process at
        /// type init, and the table hands the same instance to every materialization.</summary>
        private static void AppendSiteFields(StringBuilder sb, IReadOnlyList<EmittedTemplate> templates)
        {
            foreach (var template in templates)
            {
                if (template.Sites == null)
                    continue;
                foreach (var site in template.Sites)
                {
                    sb.Append("        private static readonly ").Append(site.DelegateType).Append(" ")
                        .Append(site.FieldName).Append(" = ");
                    if (site.MethodName != null)
                        sb.Append(site.MethodName);
                    else
                        sb.Append(site.MethodCode);
                    sb.Append(";\n");
                }
            }
        }

        private static void AppendSiteMethods(StringBuilder sb, IReadOnlyList<EmittedTemplate> templates)
        {
            foreach (var template in templates)
            {
                if (template.Sites == null)
                    continue;
                foreach (var site in template.Sites)
                {
                    if (site.MethodName == null || site.MethodCode == null)
                        continue;
                    sb.Append('\n');
                    sb.Append(site.MethodCode);
                }
            }
        }

        private static void AppendCSharpClasses(StringBuilder sb, IReadOnlyList<EmittedTemplate> templates)
        {
            bool any = false;
            foreach (var template in templates)
            {
                if (template.CSharpClasses == null || template.CSharpClasses.Count == 0)
                    continue;
                any = true;
                break;
            }

            if (!any)
                return;
            sb.Append('\n');
            sb.Append("namespace Heddle.Runtime\n{\n");
            foreach (var template in templates)
            {
                if (template.CSharpClasses == null)
                    continue;
                foreach (var cls in template.CSharpClasses)
                    sb.Append(cls);
            }

            sb.Append("}\n");
        }

        /// <summary>The design-time stubs: every wrapper declared with bodies that throw, so the
        /// intermediate compile type-checks references without running the engine. The model
        /// parameter is <c>object</c>: same-project models are unresolvable until the intermediate
        /// assembly exists, and a stub that named them would not compile.</summary>
        internal static void WriteStubs(string sourceOut, string generatedNamespace,
            IReadOnlyList<StubTemplate> templates)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated>Printed by heddle compile --stubs-only; do not edit.</auto-generated>\n");
            sb.Append("#pragma warning disable\n");
            sb.Append("using System;\n");
            sb.Append("using System.IO;\n");
            sb.Append('\n');
            sb.Append("namespace ").Append(generatedNamespace).Append("\n{\n");
            foreach (var template in templates)
            {
                sb.Append("    public static class ").Append(template.Sanitized).Append('\n');
                sb.Append("    {\n");
                sb.Append("        public static string Generate(")
                    .Append("object model, object chained = null, object callerData = null)\n");
                sb.Append("        {\n");
                sb.Append("            throw new InvalidOperationException(\"Precompiled stub.\");\n");
                sb.Append("        }\n");
                sb.Append('\n');
                sb.Append("        public static void Generate(")
                    .Append("object model, TextWriter writer, object chained = null, object callerData = null)\n");
                sb.Append("        {\n");
                sb.Append("            throw new InvalidOperationException(\"Precompiled stub.\");\n");
                sb.Append("        }\n");
                sb.Append('\n');
                sb.Append("        public static void Generate(")
                    .Append("object model, System.Buffers.IBufferWriter<byte> writer, ")
                    .Append("object chained = null, object callerData = null)\n");
                sb.Append("        {\n");
                sb.Append("            throw new InvalidOperationException(\"Precompiled stub.\");\n");
                sb.Append("        }\n");
                sb.Append("    }\n");
            }

            sb.Append("}\n");
            string directory = Path.GetDirectoryName(sourceOut);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);
            File.WriteAllText(sourceOut, sb.ToString(), new UTF8Encoding(false));
        }

        private static string Escape(string value) =>
            value.Replace("\\", "\\\\").Replace("\"", "\\\"");

        internal sealed class EmittedTemplate
        {
            internal string Key;
            internal string Sanitized;
            internal string ModelTypeName;
            internal string ContentHash = string.Empty;
            internal int TemplateIndex;
            internal bool EmitWrapper = true;
            internal readonly List<Sites.PrintedSite> Sites = new List<Sites.PrintedSite>();
            internal readonly List<Sites.SiteDecline> Declines = new List<Sites.SiteDecline>();
            internal readonly List<string> CSharpClasses = new List<string>();
            internal readonly List<string> CSharpUsings = new List<string>();
        }

        internal sealed class StubTemplate
        {
            internal string Sanitized;
            internal string ModelTypeName;
        }
    }
}
