// <copyright file="MethodExtensionTest.ProcessData.g.cs" company="Aliaksandr Kukrash">Copyright © 2012 Aliaksandr Kukrash</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Templates.Exceptions;

namespace Templates.Extensions
{
    public partial class MethodExtensionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MethodExtensionTest))]
[ExpectedException(typeof(TemplateProcessingException))]
public void ProcessDataThrowsTemplateProcessingException983()
{
    MethodExtension methodExtension;
    object o;
    methodExtension = new MethodExtension();
    o = this.ProcessData(methodExtension, (object)null, (object)null);
}
    }
}
