// <copyright file="MethodExtensionTest.InitializeInnerTemplate.g.cs" company="Aliaksandr Kukrash">Copyright © 2012 Aliaksandr Kukrash</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Templates.Core;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Templates.Exceptions;
using Microsoft.Pex.Framework.Pointers;

namespace Templates.Extensions
{
    public partial class MethodExtensionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MethodExtensionTest))]
[ExpectedException(typeof(TemplateCompileException))]
public void InitializeInnerTemplateThrowsTemplateCompileException226()
{
    MethodExtension methodExtension;
    Type type;
    methodExtension = new MethodExtension();
    type = this.InitializeInnerTemplate(methodExtension, (FastString)null, 
                                        (Type)null, (Type)null, (CompileContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(MethodExtensionTest))]
[ExpectedException(typeof(TemplateCompileException))]
public unsafe void InitializeInnerTemplateThrowsTemplateCompileException90()
{
    /* 
    MethodExtension methodExtension;
    FastString fastString;
    Type type;
    uint @base = 245366784u;
    PexPointerSpace.Initialize(new UIntPtr(@base), new UIntPtr(65536u));
    methodExtension = new MethodExtension();
    fastString = new FastString(unchecked((char*)0), 0);
    type = this.InitializeInnerTemplate
               (methodExtension, fastString, (Type)null, (Type)null, (CompileContext)null);
    PexPointerSpace.Validate();
    */
}
[TestMethod]
[PexGeneratedBy(typeof(MethodExtensionTest))]
[ExpectedException(typeof(TemplateCompileException))]
public unsafe void InitializeInnerTemplateThrowsTemplateCompileException816()
{
    /* 
    MethodExtension methodExtension;
    FastString fastString;
    Type type;
    uint @base = 245366784u;
    PexPointerSpace.Initialize(new UIntPtr(@base), new UIntPtr(65536u));
    methodExtension = new MethodExtension();
    fastString = new FastString(unchecked((char*)245399613), 1);
    type = this.InitializeInnerTemplate
               (methodExtension, fastString, (Type)null, (Type)null, (CompileContext)null);
    PexPointerSpace.Validate();
    */
}
    }
}
