// <copyright file="ModelExtensionTest.InitializeInnerTemplate.g.cs" company="Aliaksandr Kukrash">Copyright © 2012 Aliaksandr Kukrash</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Templates.Core;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Templates.Exceptions;
using Microsoft.Pex.Framework.Pointers;

namespace Templates.Extensions
{
    public partial class ModelExtensionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ModelExtensionTest))]
[ExpectedException(typeof(TemplateInitException))]
public void InitializeInnerTemplateThrowsTemplateInitException588()
{
    ModelExtension modelExtension;
    Type type;
    modelExtension = new ModelExtension();
    type = this.InitializeInnerTemplate(modelExtension, (FastString)null, 
                                        (Type)null, (Type)null, (CompileContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(ModelExtensionTest))]
[ExpectedException(typeof(TemplateInitException))]
public unsafe void InitializeInnerTemplateThrowsTemplateInitException747()
{
    /* 
    ModelExtension modelExtension;
    FastString fastString;
    Type type;
    uint @base = 253755392u;
    PexPointerSpace.Initialize(new UIntPtr(@base), new UIntPtr(65536u));
    modelExtension = new ModelExtension();
    fastString = new FastString(unchecked((char*)253788221), 1);
    type = this.InitializeInnerTemplate
               (modelExtension, fastString, (Type)null, (Type)null, (CompileContext)null);
    PexPointerSpace.Validate();
    */
}
    }
}
