// <copyright file="ReflectionHelperTest.ResolveType.g.cs" company="Aliaksandr Kukrash">Copyright © 2012 Aliaksandr Kukrash</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Templates.Exceptions;

namespace Templates.Core
{
    public partial class ReflectionHelperTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ReflectionHelperTest))]
[ExpectedException(typeof(ArgumentException))]
public void ResolveTypeThrowsArgumentException735()
{
    Type type;
    string[] ss = new string[0];
    type = this.ResolveType((string)null, (IEnumerable<string>)ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ReflectionHelperTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ResolveTypeThrowsArgumentNullException344()
{
    Type type;
    type = this.ResolveType((string)null, (IEnumerable<string>)null);
}
    }
}
